// Code generated by protoc-gen-grpchan. DO NOT EDIT.
// source: grpchantesting/test.proto

package grpchantesting

import "github.com/fullstorydev/grpchan"

func RegisterHandlerTestService(reg grpchan.ServiceRegistry, srv TestServiceServer) {
	reg.RegisterService(&_TestService_serviceDesc, srv)
}
