// Code generated by protoc-gen-go. DO NOT EDIT.
// source: httpgrpc.proto

/*
Package httpgrpc is a generated protocol buffer package.

It is generated from these files:
	httpgrpc.proto

It has these top-level messages:
	HttpTrailer
	TrailerValues
*/
package httpgrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// HttpTrailer is the last message sent in a streaming GRPC-over-HTTP
// call, to encode the GRPC status code and any trailer metadata. This
// message is only used in GRPC responses, not in requests.
type HttpTrailer struct {
	Metadata             map[string]*TrailerValues `protobuf:"bytes,1,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Code                 int32                     `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Message              string                    `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `protobuf_unrecognized:"proto3" json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *HttpTrailer) Reset()                    { *m = HttpTrailer{} }
func (m *HttpTrailer) String() string            { return proto.CompactTextString(m) }
func (*HttpTrailer) ProtoMessage()               {}
func (*HttpTrailer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }
func (m *HttpTrailer) Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpTrailer.Unmarshal(m, b)
}
func (m *HttpTrailer) Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpTrailer.Marshal(b, m, deterministic)
}
func (dst *HttpTrailer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpTrailer.Merge(dst, src)
}
func (m *HttpTrailer) XXX_Size() int {
	return xxx_messageInfo_HttpTrailer.Size(m)
}
func (m *HttpTrailer) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpTrailer.DiscardUnknown(m)
}

var xxx_messageInfo_HttpTrailer proto.InternalMessageInfo

func (m *HttpTrailer) GetMetadata() map[string]*TrailerValues {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *HttpTrailer) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HttpTrailer) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TrailerValues struct {
	Values               []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `protobuf_unrecognized:"proto3" json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrailerValues) Reset()                    { *m = TrailerValues{} }
func (m *TrailerValues) String() string            { return proto.CompactTextString(m) }
func (*TrailerValues) ProtoMessage()               {}
func (*TrailerValues) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }
func (m *TrailerValues) Unmarshal(b []byte) error {
	return xxx_messageInfo_TrailerValues.Unmarshal(m, b)
}
func (m *TrailerValues) Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrailerValues.Marshal(b, m, deterministic)
}
func (dst *TrailerValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrailerValues.Merge(dst, src)
}
func (m *TrailerValues) XXX_Size() int {
	return xxx_messageInfo_TrailerValues.Size(m)
}
func (m *TrailerValues) XXX_DiscardUnknown() {
	xxx_messageInfo_TrailerValues.DiscardUnknown(m)
}

var xxx_messageInfo_TrailerValues proto.InternalMessageInfo

func (m *TrailerValues) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*HttpTrailer)(nil), "fullstorydev.grpchan.httpgrpc.HttpTrailer")
	proto.RegisterMapType((map[string]*TrailerValues)(nil), "fullstorydev.grpchan.httpgrpc.HttpTrailer.MetadataEntry")
	proto.RegisterType((*TrailerValues)(nil), "fullstorydev.grpchan.httpgrpc.TrailerValues")
}

func init() { proto.RegisterFile("httpgrpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x28, 0x29, 0x29,
	0x48, 0x2f, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x4d, 0x2b, 0xcd, 0xc9,
	0x29, 0x2e, 0xc9, 0x2f, 0xaa, 0x4c, 0x49, 0x2d, 0xd3, 0x03, 0x49, 0x64, 0x24, 0xe6, 0xe9, 0xc1,
	0x14, 0x29, 0xfd, 0x61, 0xe4, 0xe2, 0xf6, 0x28, 0x29, 0x29, 0x08, 0x29, 0x4a, 0xcc, 0xcc, 0x49,
	0x2d, 0x12, 0x0a, 0xe1, 0xe2, 0xc8, 0x4d, 0x2d, 0x49, 0x4c, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x54,
	0x60, 0xd6, 0xe0, 0x36, 0xb2, 0xd0, 0xc3, 0x6b, 0x82, 0x1e, 0x92, 0x6e, 0x3d, 0x5f, 0xa8, 0x56,
	0xd7, 0xbc, 0x92, 0xa2, 0xca, 0x20, 0xb8, 0x49, 0x42, 0x42, 0x5c, 0x2c, 0xc9, 0xf9, 0x29, 0xa9,
	0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x60, 0xb6, 0x90, 0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71,
	0x71, 0x62, 0x7a, 0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x8c, 0x2b, 0x95, 0xc9, 0xc5,
	0x8b, 0x62, 0x90, 0x90, 0x00, 0x17, 0x73, 0x76, 0x6a, 0xa5, 0x04, 0x23, 0x58, 0x19, 0x88, 0x29,
	0xe4, 0xc4, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x0a, 0x31, 0x91, 0xdb, 0x48, 0x87, 0x80, 0x1b, 0xa1,
	0xee, 0x0b, 0x03, 0x69, 0x29, 0x0e, 0x82, 0x68, 0xb5, 0x62, 0xb2, 0x60, 0x54, 0x52, 0xe7, 0xe2,
	0x45, 0x91, 0x13, 0x12, 0xe3, 0x62, 0x03, 0xcb, 0x16, 0x83, 0x7d, 0xcf, 0x19, 0x04, 0xe5, 0x39,
	0x71, 0x45, 0x71, 0xc0, 0x4c, 0x4b, 0x62, 0x03, 0x87, 0xac, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x48, 0x95, 0x25, 0xc5, 0x6b, 0x01, 0x00, 0x00,
}
