// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: httpgrpc.proto

package httpgrpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// HttpTrailer is the last message sent in a streaming GRPC-over-HTTP
// call, to encode the GRPC status code and any trailer metadata. This
// message is only used in GRPC responses, not in requests.
type HttpTrailer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata map[string]*TrailerValues `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Code     int32                     `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message  string                    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Details  []*anypb.Any              `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *HttpTrailer) Reset() {
	*x = HttpTrailer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_httpgrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpTrailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpTrailer) ProtoMessage() {}

func (x *HttpTrailer) ProtoReflect() protoreflect.Message {
	mi := &file_httpgrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpTrailer.ProtoReflect.Descriptor instead.
func (*HttpTrailer) Descriptor() ([]byte, []int) {
	return file_httpgrpc_proto_rawDescGZIP(), []int{0}
}

func (x *HttpTrailer) GetMetadata() map[string]*TrailerValues {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HttpTrailer) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HttpTrailer) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HttpTrailer) GetDetails() []*anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

type TrailerValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *TrailerValues) Reset() {
	*x = TrailerValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_httpgrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrailerValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrailerValues) ProtoMessage() {}

func (x *TrailerValues) ProtoReflect() protoreflect.Message {
	mi := &file_httpgrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrailerValues.ProtoReflect.Descriptor instead.
func (*TrailerValues) Descriptor() ([]byte, []int) {
	return file_httpgrpc_proto_rawDescGZIP(), []int{1}
}

func (x *TrailerValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_httpgrpc_proto protoreflect.FileDescriptor

var file_httpgrpc_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x68, 0x74, 0x74, 0x70, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1d, 0x66, 0x75, 0x6c, 0x6c, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x65, 0x76, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x68, 0x61, 0x6e, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x67, 0x72, 0x70, 0x63, 0x1a,
	0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x02, 0x0a, 0x0b, 0x48,
	0x74, 0x74, 0x70, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x12, 0x54, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x66,
	0x75, 0x6c, 0x6c, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x65, 0x76, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x68, 0x61, 0x6e, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x74, 0x74,
	0x70, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e,
	0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x69,
	0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x42, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2c, 0x2e, 0x66, 0x75, 0x6c, 0x6c, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x64, 0x65, 0x76, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x68, 0x61, 0x6e, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x27, 0x0a, 0x0d, 0x54, 0x72, 0x61,
	0x69, 0x6c, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x68, 0x74, 0x74, 0x70, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_httpgrpc_proto_rawDescOnce sync.Once
	file_httpgrpc_proto_rawDescData = file_httpgrpc_proto_rawDesc
)

func file_httpgrpc_proto_rawDescGZIP() []byte {
	file_httpgrpc_proto_rawDescOnce.Do(func() {
		file_httpgrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_httpgrpc_proto_rawDescData)
	})
	return file_httpgrpc_proto_rawDescData
}

var file_httpgrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_httpgrpc_proto_goTypes = []interface{}{
	(*HttpTrailer)(nil),   // 0: fullstorydev.grpchan.httpgrpc.HttpTrailer
	(*TrailerValues)(nil), // 1: fullstorydev.grpchan.httpgrpc.TrailerValues
	nil,                   // 2: fullstorydev.grpchan.httpgrpc.HttpTrailer.MetadataEntry
	(*anypb.Any)(nil),     // 3: google.protobuf.Any
}
var file_httpgrpc_proto_depIdxs = []int32{
	2, // 0: fullstorydev.grpchan.httpgrpc.HttpTrailer.metadata:type_name -> fullstorydev.grpchan.httpgrpc.HttpTrailer.MetadataEntry
	3, // 1: fullstorydev.grpchan.httpgrpc.HttpTrailer.details:type_name -> google.protobuf.Any
	1, // 2: fullstorydev.grpchan.httpgrpc.HttpTrailer.MetadataEntry.value:type_name -> fullstorydev.grpchan.httpgrpc.TrailerValues
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_httpgrpc_proto_init() }
func file_httpgrpc_proto_init() {
	if File_httpgrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_httpgrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpTrailer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_httpgrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrailerValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_httpgrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_httpgrpc_proto_goTypes,
		DependencyIndexes: file_httpgrpc_proto_depIdxs,
		MessageInfos:      file_httpgrpc_proto_msgTypes,
	}.Build()
	File_httpgrpc_proto = out.File
	file_httpgrpc_proto_rawDesc = nil
	file_httpgrpc_proto_goTypes = nil
	file_httpgrpc_proto_depIdxs = nil
}
